package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"log"
	"strconv"
	"tarikihongan-todo/db"
	"tarikihongan-todo/models"

	"github.com/volatiletech/sqlboiler/v4/boil"
)

// CreateTodo is the resolver for the CreateTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, userID string, title string) (*models.Response, error) {
	intUserID, err := strconv.Atoi(userID)
	if err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}
	todo := models.Todo{
		Title:         title,
		CreatedUserID: intUserID,
	}
	if err := todo.Insert(ctx, db.DB, boil.Infer()); err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}

	successMeg := "Todo created successfully."
	return &models.Response{Success: true, Message: &successMeg}, nil
}

// UpdateTodo is the resolver for the UpdateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, title string) (*models.Response, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}
	qm := models.TodoWhere.ID.EQ(intID)
	todo, err := models.Todos(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}
	todo.Title = title
	if _, err := todo.Update(ctx, db.DB, boil.Infer()); err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}

	successMeg := "Todo updated successfully."
	return &models.Response{Success: true, Message: &successMeg}, nil
}

// DeleteTodo is the resolver for the DeleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*models.Response, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}
	qm := models.TodoWhere.ID.EQ(intID)
	todo, err := models.Todos(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}
	if _, err := todo.Delete(ctx, db.DB); err != nil {
		log.Fatal(err)
		errMeg := err.Error()
		return &models.Response{Success: false, Message: &errMeg}, err
	}

	successMeg := "Todo deleted successfully."
	return &models.Response{Success: true, Message: &successMeg}, nil
}

// Todos is the resolver for the Todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*models.Todo, error) {
	todos, err := models.Todos().All(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	return todos, nil
}

// TodoByID is the resolver for the TodoByID field.
func (r *queryResolver) TodoByID(ctx context.Context, id string) (*models.Todo, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	qm := models.TodoWhere.ID.EQ(intID)
	todo, err := models.Todos(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	return todo, nil
}

// TodoByCreatedUser is the resolver for the TodoByCreatedUser field.
func (r *queryResolver) TodoByCreatedUser(ctx context.Context, userID *string) ([]*models.Todo, error) {
	intID, err := strconv.Atoi(*userID)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	qm := models.TodoWhere.CreatedUserID.EQ(intID)
	todos, err := models.Todos(qm).All(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	return todos, nil
}

// CreatedUser is the resolver for the created_user field.
func (r *todoResolver) CreatedUser(ctx context.Context, obj *models.Todo) (*models.User, error) {
	qm := models.UserWhere.ID.EQ(obj.CreatedUserID)
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	return user, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *todoResolver) CreatedAt(ctx context.Context, obj *models.Todo) (string, error) {
	return obj.CreatedAt.String(), nil
}

// Mutation returns db.MutationResolver implementation.
func (r *Resolver) Mutation() db.MutationResolver { return &mutationResolver{r} }

// Query returns db.QueryResolver implementation.
func (r *Resolver) Query() db.QueryResolver { return &queryResolver{r} }

// Todo returns db.TodoResolver implementation.
func (r *Resolver) Todo() db.TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
