package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"log"
	"strconv"
	"tarikihongan-todo/db"
	"tarikihongan-todo/models"

	"github.com/volatiletech/sqlboiler/v4/boil"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string, password string) (*models.User, error) {
	user := &models.User{
		Name:     name,
		Email:    email,
		Password: bcryptPassword(password),
	}
	if err := user.Insert(ctx, db.DB, boil.Infer()); err != nil {
		log.Fatalln(err)
		return nil, err
	}
	return user, nil
}

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string) (*models.User, error) {
	convID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	qm := models.UserWhere.ID.EQ(convID)
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	user.Name = name
	if _, err := user.Update(ctx, db.DB, boil.Infer()); err != nil {
		log.Fatalln(err)
		return nil, err
	}
	return user, nil
}

// DeleteUser is the resolver for the DeleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*models.User, error) {
	convID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	qm := models.UserWhere.ID.EQ(convID)
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	if _, err := user.Delete(ctx, db.DB); err != nil {
		log.Fatalln(err)
		return nil, err
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	users, err := models.Users().All(ctx, db.DB)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	convID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	qm := models.UserWhere.ID.EQ(convID)
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	return user, nil
}

// Mutation returns db.MutationResolver implementation.
func (r *Resolver) Mutation() db.MutationResolver { return &mutationResolver{r} }

// Query returns db.QueryResolver implementation.
func (r *Resolver) Query() db.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
