package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"log"
	"strconv"
	"tarikihongan-todo/db"
	"tarikihongan-todo/models"
	"tarikihongan-todo/usecase"

	"github.com/volatiletech/sqlboiler/v4/boil"
)

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, name string) (*models.Response, error) {
	userId, success := usecase.GetCache("user_id")
	if !success {
		errMsg := "User not found."
		return &models.Response{Success: false, Message: &errMsg}, nil
	}

	qm := models.UserWhere.ID.EQ(userId.(int))
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		errMsg := err.Error()
		return &models.Response{Success: false, Message: &errMsg}, err
	}

	user.Name = name
	if _, err := user.Update(ctx, db.DB, boil.Infer()); err != nil {
		log.Fatalln(err)
		errMsg := err.Error()
		return &models.Response{Success: false, Message: &errMsg}, err
	}

	message := "User updated successfully."
	return &models.Response{Success: true, Message: &message}, nil
}

// DeleteUser is the resolver for the DeleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (*models.Response, error) {
	userId, success := usecase.GetCache("user_id")
	if !success {
		errMsg := "User not found."
		return &models.Response{Success: false, Message: &errMsg}, nil
	}

	qm := models.UserWhere.ID.EQ(userId.(int))
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		errMsg := err.Error()
		return &models.Response{Success: false, Message: &errMsg}, err
	}

	if _, err := user.Delete(ctx, db.DB); err != nil {
		log.Fatalln(err)
		errMsg := err.Error()
		return &models.Response{Success: false, Message: &errMsg}, err
	}
	message := "User delete successfully."
	return &models.Response{Success: true, Message: &message}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	users, err := models.Users().All(ctx, db.DB)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	convID, err := strconv.Atoi(id)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	qm := models.UserWhere.ID.EQ(convID)
	user, err := models.Users(qm).One(ctx, db.DB)
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	return user, nil
}
