development:
  dialect: postgres
  datasource: host=db port=5432 user=tarikihongan password=password dbname=tarikihongan-db sslmode=disable
  dir: db/migrations
  table: gorp_migrations

production:
  dialect: postgres
  datasource: host=$DB_HOST port=$DB_PORT user=$DB_USER password=$DB_PASSWORD dbname=$DB_NAME
  dir: db/migrations
  table: migrations
