// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type Query struct {
}

type Response struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}
